name: esus

services:
  flask_esus:
    container_name: flask_esus
    image: esus/flask_esus_api:1.0
    build: .
    ports:
      - "8001:8001"
    environment:
      - DB_URL=${SQLALCHEMY_DATABASE_URI}

    depends_on:
      - postgres_esus

  postgres_esus:
    container_name: postgres_esus
    image: postgres:15.3-alpine
    platform: linux/x86_64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
